### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by CrafterLTU** [bapeoriginals/BorderX#1]
Its a pretty good plugin. i noticed its a circle type border, is it possible to make it like a square border? like maybe add a setting for that which switches between a square border and a circle border, would that be possible? If not its still a useful plugin, will be using this for some projects

**Comment by CrafterLTU** [comment]
Also just noticed a bit of a problem, the LevelName doesn't work and it registers the border to all of the worlds, making all worlds with a border which i dont want

**Comment by bapeoriginals** [comment]
Hey, thanks for your suggestion, but I don’t have time anymore and I’m not working anymore to fix something, sorry about that!
